### ISSUE TITLE
Image viewer text is barely visible

### ISSUE THREAD

**Issue by marcelgerber** [Brackets-Themes/TomorrowNight#1]
![image](https://cloud.githubusercontent.com/assets/2641501/4078083/aed7a9d4-2ec8-11e4-86a7-f6a642cd811c.png)
The text is barely visible (Release 0.43)

**Comment by marcelgerber** [comment]
This issue was fixed as the `#image-holder` doesn't exist any more.
Therefore, we can remove the whole rule now (cc @wormeyman)

**Comment by wormeyman** [comment]
It is `.image-view` now if that matters.

**Comment by marcelgerber** [comment]
I guess it's fine to completely remove the rules...
